### PR TITLE
Re-add description and author as title-slide

### PR DESCRIPTION
**Pull request by vitorbal**
Took a stab at re-adding the title-slide, with the author's name, gravatar and the gist description

### CODE REVIEW

**Comment by nzoschke** [comment]
Awesome! There's an extra trailing slash after the author, is it hard to get rid of that?

**Comment by vitorbal** [comment]
I'm not sure, i'll have to do some experimenting.. I'll give it a try
tomorrow though

**Comment by vitorbal** [comment]
done!

**Comment by nzoschke** [comment]
Brilliant. Thanks!

**Comment by nzoschke** [comment]
Just noticed that escape doesn't fully reset everything after these style rules. Will dig into it later.

**Comment by nzoschke** [comment]
Fixed in 2b322ea1

**Comment by vitorbal** [comment]
Oops, my bad!

**Pull request merged**
