### PR TITLE
Make gistdeck work for any viewport size and fix vertical centering.

### PR DESCRIPTION
**Pull request by henrahmagix**

### CODE REVIEW

**Comment by henrahmagix** [comment]
This fixes #4. I worked off the commits in #15 then rebased back to master, so that I could create two pull-requests that don't include each other's commits. Because of this, gistdeck.js has the same change to the last line (due to no newline at EOF) in two commits: one here and one in #15.

However, I tested it and it all merges fine =)

**Comment by nzoschke** [comment]
Thanks for the PR. It merges cleanly. But I'll need to do a bit more testing on different size displays before I can release this.

**Comment by nzoschke** [comment]
These commits are in, but I somehow picked them up without merging this PR. Weird.

Haven't tested much on larger displays, but still works on my 11" air, and the logic is sound. Thanks!

**Comment by henrahmagix** [comment]
You're welcome =)

**Pull request closed without merging**
